[project]
name = "groceries-basket-analysis"
version = "0.1.0"
description = "The project is about performing market basket analysis using Pythong and Power BI"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.3",
    "numpy>=2.3.1",
    "pandas>=2.3.1",
    "python-box>=7.3.2",
    "pyyaml>=6.0.2",
    "rich>=14.0.0",
    "seaborn>=0.13.2",
]

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
    "pre-commit>=4.0.1",
    "pytest>=8.4.1",
    "pytest-cov>=6.2.1",
    "ruff>=0.12.3",
]
